anteiku/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('category/', include('category.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

category/urls.py
from django.urls import path
from category.views import CategoryCreateView, CategoryListView, CategoryUpdateView, \
    CategoryDeleteView, CategoryDetailView


urlpatterns = [
    path('category-add/', CategoryCreateView.as_view(), name='category_add'),
    path('category-list/', CategoryListView.as_view(), name='category_list'),
    path('category-edit/<int:pk>/', CategoryUpdateView.as_view(), name='category_edit'),
    path('category-delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    path('category-details/<int:pk>/', CategoryDetailView.as_view(), name='category_details'),
]

home/urls.py
from django.urls import path
from home.views import HomePageTemplateView


urlpatterns = [
    path('', HomePageTemplateView.as_view(), name='home')
]

users/urls.py
from django.urls import path
from users import views


urlpatterns = [
    path('user-sign-up/', views.sign_up, name='users-create')
]

category/models.py
from django.db import models


class Category(models.Model):
    category_name = models.CharField(max_length=150)
    category_description = models.CharField(max_length=450)
    category_image = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.category_name


class SubCategory(models.Model):
    sub_category_name = models.CharField(max_length=150)
    sub_category_description = models.CharField(max_length=450)

    def __str__(self):
        return self.sub_category_name

home/models.py
from django.db import models

# Create your models here.

users/models.py
from creditcards.models import CardNumberField, CardExpiryField, SecurityCodeField
from django.contrib.auth.models import User
from django.db import models


class ExtendUser(User):
    phone_number = models.CharField(max_length=100)
    address = models.CharField(max_length=450)
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=100)


class Payment(models.Model):
    cc_type = models.CharField(max_length=100)
    cc_number = CardNumberField('card number')
    cc_expiry = CardExpiryField('expiration date')
    cc_code = SecurityCodeField('security code')

    def __str__(self):
        return self.cc_type

category/forms.py
from django import forms
from django.forms import TextInput
from category.models import Category


class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            'category_name',
            'category_description'
        ]
        widgets = {
            'category_name': TextInput(attrs={
                'placeholder': 'Please insert category name',
                'class': 'input is-primary'
            }),
            'category_description': TextInput(attrs={
                'placeholder': 'Please insert a description',
                'class': 'input is-primary'
            })
        }

    def __init__(self, *args, **kwargs):
        super(CategoryCreateForm, self).__init__(*args, **kwargs)
        self.fields['category_name'].required = True
        self.fields['category_description'].required = False

    def clean(self):
        cleaned_data = self.cleaned_data
        name = cleaned_data.get('category_name')
        # description = cleaned_data.get('category_description')
        all_categories = Category.objects.all()
        for category in all_categories:
            if name == category.category_name:
                msg = 'Category is already present in Database'
                self._errors['category_name'] = self.error_class([msg])
        return cleaned_data

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import TextInput
from users.models import ExtendUser


class UserCreateForm(UserCreationForm):
    class Meta:
        model = ExtendUser
        fields = ['first_name', 'last_name', 'username', 'email', 'phone_number', 'address',
                  'city', 'country', 'postal_code']
        widgets = {
            'first_name': TextInput(attrs={
                'placeholder': 'Please type your first name here',
                'class': 'input is-primary'
            }),
            'last_name': TextInput(attrs={
                'placeholder': 'Please type your last name here',
                'class': 'input is-primary'
            }),
            'username': TextInput(attrs={
                'placeholder': 'Please type your username here',
                'class': 'input is-primary'
            }),
            'email': TextInput(attrs={
                'placeholder': 'Please type your email here',
                'class': 'input is-primary'
            }),
            'phone_number': TextInput(attrs={
                'placeholder': 'Please type your phone number here',
                'class': 'input is-primary'
            }),
            'address': TextInput(attrs={
                'placeholder': 'Please type your address here',
                'class': 'input is-primary'
            }),
            'city': TextInput(attrs={
                'placeholder': 'Please type your city here',
                'class': 'input is-primary'
            }),
            'country': TextInput(attrs={
                'placeholder': 'Please type your country here',
                'class': 'input is-primary'
            }),
            'postal_code': TextInput(attrs={
                'placeholder': 'Please type your postal code here',
                'class': 'input is-primary'
            }),
        }

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs['class'] = 'input is-primary'
        self.fields['password1'].widget.attrs['placeholder'] = 'Please insert password'
        self.fields['password2'].widget.attrs['class'] = 'input is-primary'
        self.fields['password2'].widget.attrs['placeholder'] = 'Please insert password confirmation'

    def clean(self):
        cleaned_data = self.cleaned_data
        username = cleaned_data.get('username')
        email = cleaned_data.get('email')
        all_users = ExtendUser.objects.all()
        for user in all_users:
            if username == user.username:
                msg = 'username already taken'
                self._errors['username'] = self.error_class([msg])
            if email == user.email:
                msg = 'this email is already connected to an account'
                self._errors['email'] = self.error_class([msg])
        return cleaned_data

category/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from category.forms import CategoryCreateForm
from category.models import Category


class CategoryCreateView(CreateView):
    template_name = 'category/category_add.html'
    model = Category
    form_class = CategoryCreateForm
    success_url = reverse_lazy('category_list')


class CategoryListView(ListView):
    template_name = 'category/category_list.html'
    model = Category
    context_object_name = 'all_categories'


class CategoryUpdateView(UpdateView):
    template_name = 'category/category_edit.html'
    model = Category
    fields = '__all__'
    success_url = reverse_lazy('category_list')


class CategoryDeleteView(DeleteView):
    template_name = 'category/category_delete.html'
    model = Category
    success_url = reverse_lazy('category_list')


class CategoryDetailView(DetailView):
    template_name = 'category/category_details.html'
    model = Category
    context_object_name = 'category_details'

home/views.py
from django.views.generic import TemplateView


class HomePageTemplateView(TemplateView):
    template_name = 'home_page/main_page.html'

users/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render
from users.forms import UserCreateForm


def sign_up(request):
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = UserCreateForm
    return render(request, 'registration/sign_up.html', {'form': form})

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">

    <! -- CSS files -->
    <link rel="stylesheet" href="{% static 'CSS/shop_style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">

    <title>{% block title %} {% endblock %}</title>

    <! -- JS files -->
    <script type="text/javascript" src="{% static 'JS/shop_js.js' %}"></script>

</head>
<body>

    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="https://bulma.io">
                <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28" alt="">
            </a>

            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href={% url 'home' %}>
                    Home
                </a>

                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                        About
                    </a>

                    <div class="navbar-dropdown">
                        <a class="navbar-item">
                            Our Story
                        </a>
                        <a class="navbar-item">
                            Events
                        </a>
                        <a class="navbar-item">
                            Blog
                        </a>
                    </div>
                </div>

                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                        Shop
                    </a>

                    <div class="navbar-dropdown">
                        <a class="navbar-item">
                            Coffee
                        </a>
                        <a class="navbar-item">
                            Tea
                        </a>
                        <a class="navbar-item">
                            Pastry
                        </a>
                    </div>
                </div>
                <a class="navbar-item">
                    Contact
                </a>
                <a class="navbar-item">
                    Meniu
                </a>
                {% if perms.category.view_category %}
                <a class="navbar-item" href={% url 'category_list' %}>Categories</a>
                {% endif %}
        </div>

            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">
                    {% if user.is_authenticated %}
                    <a href="{% url 'logout' %}" class="button is-primary">
                        Logout, {{ request.user.username }}
                    </a>
                    {% else %}
                    <a href="{% url 'users-create' %}" class="button is-primary">
                        <strong>Sign up</strong>
                    </a>
                    <a href="{% url 'login' %}" class="button is-primary">
                        <strong>Login</strong>
                    </a>
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </nav>

    {% block content %} {% endblock %}

</body>
</html>

templates/category/category_add.html
{% extends 'base.html' %}
{% block title %}Category add{% endblock %}
{% block content %}

    <form method="post" action="">
        {% csrf_token %}
        {% for field in form %}
            <div class="field">
                <label class="label">{{ field.label }}</label>
                <div class="control">
                    {{ field }}
                </div>
                <span class="color_red">
                    {{ field.errors }}
                </span>
            </div>
        {% endfor %}
        <button type="submit">Submit</button>
    </form>

{% endblock %}

templates/category/category_delete.html
{% extends 'base.html' %}
{% block title %}Category Delete{% endblock %}
{% block content %}
    <form method="post">
        <h3>Are you sure you want to delete this category?</h3>
        {% csrf_token %}
        <button type="submit">Yes</button>
        <a href={% url 'category_list' %}>No</a>
    </form>
{% endblock %}

templates/category/category_details.html
{% extends 'base.html' %}
{% block title %}Category Details{% endblock %}
{% block content %}
    <div class="container">
        <div class="section">

            <div class="card">
              <div class="card-content">
                <div class="media">
                  <div class="media-left">
                    <figure class="image is-48x48">
                      <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
                    </figure>
                  </div>
                  <div class="media-content">
                    <p class="title is-4">{{ category_details.category_name}}</p>
                  </div>
                </div>

                <div class="content">
                    <p class="subtitle is-6">{{ category_details.category_description }}</p>
                    <br>

                    <a href="{% url 'category_list' %}">Back to category list</a>
                </div>
              </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/category/category_edit.html
{% extends 'base.html' %}
{% block title %}Category Edit{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <button type="submit">Update</button>
    </form>
{% endblock %}

templates/category/category_list.html
{% extends 'base.html' %}
{% block title %}Category List{% endblock %}
{% block content %}
    <section class="section">
        <div class="container">
            <table class="table">
                <thead>
                    <tr>
                        <th>Category Name</th>
                        <th>Description</th>
                        <th>Image</th>
                    </tr>
                </thead>
                <tbody>
                    {% for entries in all_categories %}
                        <tr>
                            <td>{{ entries.category_name }}</td>
                            <td>{{ entries.category_description }}</td>
                            <td><img src="{{ entries.category_image }}" alt="missing"/></td>
                            <td>

                                    <a href="{% url 'category_edit' entries.id %}">Update</a>



                                    <a href="{% url 'category_delete' entries.id %}">Delete</a>



                                    <a href="{% url 'category_details' entries.id %}">Details</a>

                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

                <a href={% url 'category_add' %}>Add new category</a>

        </div>
    </section>
{% endblock %}

templates/home_page/main_page.html
{% extends 'base.html' %}
{% block title %}Anteiku - Home{% endblock %}
{% block content %}

{% endblock %}